[package]
name = "annonars"
version = "0.14.1"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust template repository"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/annonars"
readme = "README.md"
autobins = false

[lib]
name = "annonars"
path = "src/lib.rs"

[[bin]]
name = "annonars"
path = "src/main.rs"

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0"
bgzip = "0.3"
boolvec = "0.2"
byteorder = "1.4"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.3", features = ["derive", "env"] }
clap-verbosity-flag = "2.0"
csv = "1.2"
enum-map = { version = "2.6.1", features = ["serde"] }
env_logger = "0.10"
flate2 = "1.0"
hgvs = "0.10"
indexmap = { version = "2.0", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
log = "0.4"
noodles-bed = "0.10"
noodles-bgzf = "0.22"
noodles-core = "0.12"
noodles-csi = "0.22"
noodles-tabix = "0.26"
noodles-vcf = "0.35"
prost = "0.11"
rayon = "1.7"
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }
rocksdb-utils-lookup = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features=["preserve_order"] }
serde_with = "3.3"
strum = { version = "0.25", features = ["strum_macros", "derive"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
insta = { version = "1.31", features = ["yaml"] }
log = "0.4"
pretty_assertions = "1.4"
temp_testdir = "0.2"
test-log = "0.2"
tracing-subscriber = "0.3"
