[package]
name = "annonars"
version = "0.34.1"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust template repository"
license = "Apache-2.0"
homepage = "https://github.com/varfish-org/annonars"
readme = "README.md"
autobins = false
exclude = ["/tests"]

[lib]
name = "annonars"
path = "src/lib.rs"

[[bin]]
name = "annonars"
path = "src/main.rs"

[dependencies]
actix-web = "4.4.1"
anyhow = "1.0"
bgzip = "0.3"
bio = "1.5.0"
biocommons-bioutils = "0.1.0"
boolvec = "0.2"
byteorder = "1.4"
chrono = { version = "0.4", features = ["serde"] }
clap-verbosity-flag = "2.1"
clap = { version = "4.4", features = ["derive", "env"] }
csv = "1.2"
enum-map = { version = "2.7.3", features = ["serde"] }
env_logger = "0.11"
flate2 = "1.0"
indexmap = { version = "2.1", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
log = "0.4"
noodles-bed = "0.12"
noodles-bgzf = "0.26"
noodles-core = "0.14"
noodles-csi = "0.30"
noodles-tabix = "0.36"
noodles-vcf = "0.49"
pbjson = "0.6"
pbjson-types = "0.6"
prost = "0.12"
rayon = "1.8"
rocksdb-utils-lookup = "0.3"
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }
serde_json = { version = "1.0", features=["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.6", features=["alloc", "macros", "indexmap_2"], default-features = false }
strum = { version = "0.26", features = ["strum_macros", "derive"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
rustc-hash = "1.1.0"
noodles-gff = "0.27.0"
erased-serde = "0.4.2"

[build-dependencies]
prost-build = "0.12"
pbjson-build = "0.6"
anyhow = "1.0"

[dev-dependencies]
insta = { version = "1.33", features = ["yaml"] }
log = "0.4"
pretty_assertions = "1.4"
rstest = "0.18.2"
temp_testdir = "0.2"
test-log = "0.2"
tracing-subscriber = "0.3"
tracing-test = "0.2.4"

# Compile insta with full optimization.
[profile.dev.package.insta]
opt-level = 3
[profile.dev.package.similar]
opt-level = 3
